### ISSUE TITLE
Support bot stuck waiting for commands

### ISSUE THREAD

**Issue by StreakDragon** [Scarsz/DiscordSupportBot#14]
I have installed the support bot on many servers that I'm not the owner of, so I only recently ran into this issues after installing it on my server.  I use a lot of ellipses when I talk such as "Hi...how are you?"  and in doing so it triggered the bot to go into set up.  Since then it broke.  Now all the bot will do, no matter what I type or what channel I type it in, is output "[5:37 PM] BOT Support: Your message must be an integer.".

I attempted to kick the bot and bring it back but it continues to malfunction.  I've been forced to kick the bot all together as I can't get it to stop.

**Comment by Scarsz** [comment]
Right, that's because the bot thinks it's suppose to be setting up that guild for the support bot. The legacy bot wasn't programmed very well and the setup script often has issues. You'll just have to not use ellipses for now until the rewrite is released.

**Comment by StreakDragon** [comment]
But it's stuck in the loop and I can't get it out of it.  It fails to function at all any longer, won't respond to anything and just repeatedly says the indicated message.  I've not tried reinviting it, however.

**Comment by Scarsz** [comment]
I restarted the bot, check to see if you still have your issue.

**Comment by UndyingSoul** [comment]
Seems to no longer work, I've kicked and reinvited it and it doesn't work :'( it is the best bot out there for tickets though, love what you did with it <3
