### ISSUE TITLE
Extra setting: Allow bot messages in support creation channel.

### ISSUE THREAD

**Issue by burturt** [Scarsz/DiscordSupportBot#8]
Have a new setting like “Allow bots in support creation channel?” And if yes, delete all messages by bots and not make a ticket in the channel that you type in to create a ticket.

**Comment by Scarsz** [comment]
I don't understand what you mean by this

**Comment by burturt** [comment]
Have an extra setup setting where it asks "Allow bots?"
Yes means that any message sent in the support channel by a bot is kept, while No deletes all messages sent by bots in the support channel.

**Comment by Scarsz** [comment]
Why would this be necessary?

**Comment by Scarsz** [comment]
Closing because no response
